services:
  web:
    container_name: backend
    build:
      target: web
      context: ./backend
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
